import type { Metadata } from "next";
import { Contrail_One } from "next/font/google";

import { Footer } from "@/layout/footer";
import "./globals.css";

const contrailOne = Contrail_One({
  variable: "--font-contrial-one",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "TODOS",
  description: "Generated by 1732",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${contrailOne.variable} antialiased`}>
        <main className="content-grid mt-4 min-h-[calc(100dvh-4rem)]">
          <div className="bg-neutral-background/60 border size-full rounded-lg p-4">
            {children}
          </div>
        </main>

        <Footer />
      </body>
    </html>
  );
}
