/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ErrorImport } from './routes/error'
import { Route as TodosRouteImport } from './routes/todos/route'
import { Route as IndexImport } from './routes/index'
import { Route as TodosIdImport } from './routes/todos/$id'

// Create/Update Routes

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const TodosRouteRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodosIdRoute = TodosIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TodosRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/todos/$id': {
      id: '/todos/$id'
      path: '/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof TodosIdImport
      parentRoute: typeof TodosRouteImport
    }
  }
}

// Create and export the route tree

interface TodosRouteRouteChildren {
  TodosIdRoute: typeof TodosIdRoute
}

const TodosRouteRouteChildren: TodosRouteRouteChildren = {
  TodosIdRoute: TodosIdRoute,
}

const TodosRouteRouteWithChildren = TodosRouteRoute._addFileChildren(
  TodosRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos': typeof TodosRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/todos/$id': typeof TodosIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos': typeof TodosRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/todos/$id': typeof TodosIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/todos': typeof TodosRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/todos/$id': typeof TodosIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos' | '/error' | '/todos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos' | '/error' | '/todos/$id'
  id: '__root__' | '/' | '/todos' | '/error' | '/todos/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosRouteRoute: typeof TodosRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosRouteRoute: TodosRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/todos",
        "/error"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/todos": {
      "filePath": "todos/route.jsx",
      "children": [
        "/todos/$id"
      ]
    },
    "/error": {
      "filePath": "error.jsx"
    },
    "/todos/$id": {
      "filePath": "todos/$id.jsx",
      "parent": "/todos"
    }
  }
}
ROUTE_MANIFEST_END */
